#Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
#By starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def fibonacci(max):
    a, b = 0, 1
    numbers = [0, 1]
    while a < max:
        aux = a
        a = b
        b = aux+b
        if b < max:
            numbers.append(b)
    return numbers

def isEven():
    total = 0
    for n in fibonacci(4000000):
        if n%2 != 0:
            total = total + n
            print n
    return total

print isEven()


        